name: my_complex_nullsafety
description: naive implementation of cartesian and polar complex numbers.
version: 0.1.1
author: HAKStudio <hakstudioo@gmail.com>
homepage: https://hakstudio.com.tr

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
